# Generated by Django 4.2.29 on 2026-03-06 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم العقار')),
                ('description', models.TextField(blank=True, verbose_name='وصف العقار')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر')),
                ('location', models.CharField(max_length=300, verbose_name='الموقع')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المساحة (م²)')),
                ('property_type', models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('office', 'مكتب'), ('land', 'أرض'), ('warehouse', 'مستودع')], default='apartment', max_length=20, verbose_name='نوع العقار')),
                ('status', models.CharField(choices=[('sale', 'للبيع'), ('rent', 'للإيجار')], default='sale', max_length=10, verbose_name='الحالة')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='غرف النوم')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='الحمامات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', verbose_name='الصورة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الصورة الرئيسية')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'صورة العقار',
                'verbose_name_plural': 'صور العقارات',
            },
        ),
        migrations.CreateModel(
            name='NegotiationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='رسالتك')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف للتواصل')),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر المقترح')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('contacted', 'تم التواصل'), ('closed', 'مغلق')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب تفاوض',
                'verbose_name_plural': 'طلبات التفاوض',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مفضلة',
                'verbose_name_plural': 'المفضلات',
                'unique_together': {('user', 'property')},
            },
        ),
    ]
